version: "3.3"
services:
  test:
    build:
      context: .
    container_name: test-python
    volumes:
    - .:/opt
    command: python3 /opt/test_numpy.py
    deploy:
      resources:
        reservations:
          cpus: 1
        limits:
          cpus: 1
    # environment:
    # - OMP_NUM_THREADS=1
